site_name: OpenSSM Documentation

theme: windmill
#theme: material
#theme:
#  name: readthedocs
#  navigation_depth: 5
#  collapse_navigation: True
#  sticky_navigation: True

extra:
#  logo: path
  version: v0.1.5
  article_nav_top: true
  article_nav_bottom: true
  history_buttons: true

extra_css:
    - mkdocs.css
    - https://fonts.googleapis.com/css?family=Sofia
    - https://fonts.googleapis.com/css?family=Oswald
    - https://fonts.googleapis.com/css?family=Open+Sans

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import sys
            - sys.path.append('openssm')
            - sys.path.insert(0, os.path.abspath('.'))
            - print(sys.path)
          options:
            show_source: False
nav:
  - Home: index.md
  - Getting Started: GETTING_STARTED.md
  - Developer Guide:
    - Design Principles: dev/design_principles.md
    - Using Makefile: dev/makefile_info.md
    - Other HowTos: dev/howtos.md
  - Integrations:
    - LlamaIndex: openssm/integrations/llamaindex/README.md
    - Vectara: integrations/vectara.md
    - Lepton.AI: integrations/lepton_ai.md
  - Community:
    - Contributing: community/CONTRIBUTING.md
    - Project Philosophy: PROJECT_PHILOSOPHY.md
    - Code of Conduct: community/CODE_OF_CONDUCT.md
    - Support:
      - Support: support/README.md 
      - FAQ: support/FAQ/README.md
      - Troubleshoot: support/troubleshooting_guides/README.md
  - See Also:
    - Diagrams: diagrams/README.md
    - License: LICENSE.md
  - API Reference:

    - openssm:
      - capture: openssm/capture/EMPTY.md
      - core:
        - ssm:
          - base_ssm_builder: openssm/core/ssm/base_ssm_builder.md
          - base_ssm: openssm/core/ssm/base_ssm.md
          - abstract_ssm: openssm/core/ssm/abstract_ssm.md
          - abstract_ssm_builder: openssm/core/ssm/abstract_ssm_builder.md
        - slm:
          - abstract_slm: openssm/core/slm/abstract_slm.md
          - base_slm: openssm/core/slm/base_slm.md
          - memory:
            - conversation_db: openssm/core/slm/memory/conversation_db.md
            - sqlite_conversation_db: openssm/core/slm/memory/sqlite_conversation_db.md
        - backend:
          - abstract_backend: openssm/core/backend/abstract_backend.md
          - base_backend: openssm/core/backend/base_backend.md
          - text_backend: openssm/core/backend/text_backend.md
        - adapter:
          - abstract_adapter: openssm/core/adapter/abstract_adapter.md
          - base_adapter: openssm/core/adapter/base_adapter.md
        - inferencer:
          - base_inferencer: openssm/core/inferencer/base_inferencer.md
          - abstract_inferencer: openssm/core/inferencer/abstract_inferencer.md
      - composer: openssm/composer/EMPTY.md
      - utils:
        - config: openssm/utils/config.md
        - utils: openssm/utils/utils.md
        - logs: openssm/utils/logs.md
      - contrib:
        - ssms:
          - mri_operator_ssm: openssm/contrib/ssms/mri_operator_ssm/EMPTY.md
          - industrial_boilers_ssm: openssm/contrib/ssms/industrial_boilers_ssm/EMPTY.md
          - semiconductor_ssm: openssm/contrib/ssms/semiconductor_ssm/EMPTY.md
          - japan_fish_kcp_ssm: openssm/contrib/ssms/japan_fish_kcp_ssm/EMPTY.md
        - apps: openssm/contrib/apps/EMPTY.md
      - integrations:
        - llamaindex:
          - backend: openssm/integrations/llamaindex/backend.md
          - ssm: openssm/integrations/llamaindex/ssm.md
        - vectara: openssm/integrations/vectara/EMPTY.md
        - testing_tools: openssm/integrations/testing_tools/EMPTY.md
        - huggingface:
          - slm: openssm/integrations/huggingface/slm.md
          - ssm: openssm/integrations/huggingface/ssm.md
        - openai:
          - slm: openssm/integrations/openai/slm.md
          - ssm: openssm/integrations/openai/ssm.md
      - industrial:
        - security:
          - audit: openssm/industrial/security/audit/EMPTY.md
          - best_practices: openssm/industrial/security/best_practices/EMPTY.md
        - monitoring: openssm/industrial/monitoring/EMPTY.md
        - interpretability: openssm/industrial/interpretability/EMPTY.md
        - chatssm-vinh:
          - ssms:
            - semiconductor_ssm: openssm/deprecated/chatssm-vinh/ssms/semiconductor_ssm/EMPTY.md
          - static:
            - images: openssm/deprecated/chatssm-vinh/static/images/EMPTY.md
