[tool.poetry]
authors = ["Aitomatic Engineering <engineering@aitomatic.com>"]
description = "OpenSSM - 'Small Specialist Models' for Industrial AI"
name = "openssm"
packages = [
  {include = "openssm"},
]
readme = "README.md"
version = "0.1.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
python-dotenv = ">=0.19.0"
# LlamaIndex & related
llama-hub = ">=0.0.4"
llama-index = ">=0.6.33"
# misc / other
pypdf = ">=3.11.0"
pytest = ">=7.0.0"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
filterwarnings = [
  "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
