[tool.poetry]
authors = ["Aitomatic Engineering <engineering@aitomatic.com>"]
description = "OpenSSA - 'Small Specialist Agents' for Industrial AI"
name = "openssa"
packages = [
  {include = "openssa"},
]
readme = "README.md"
version = "0.1.6"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
python-dotenv = ">=0.19.0"
pydantic = ">=1.10"
openai = "~1.3.2"
# LlamaIndex & related
llama-hub = ">=0.0.4"
llama-index = "~0.9.2"
# misc / other
pytest = ">=7.0.0"
google-api-python-client = ">=2.0"
httpx = "^0.25.0"


[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
filterwarnings = [
  "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
  "ignore:Deprecated call to `pkg_resources.declare_namespace.*google.*:DeprecationWarning",
]
