name: Install Package, Lint Code & Run Tests

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.10'
          - 3.11

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: python3 -m pip install Poetry --upgrade

      - name: Install Package & Dependencies
        run: poetry install --extras=lint --extras=test

      - name: Lint Code
        run: make lint

      - name: Run Tests
        run: make test
        env:
          LEPTON_API_KEY: ${{ secrets.LEPTON_API_KEY }}
